config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end
  resources :news_items
  resources :news_sources
  get 'home/index'
  mount_griddler

  root 'home#index'

end

app/models/news_source.rb
class NewsSource < ActiveRecord::Base
end

app/controllers/news_sources_controller.rb
class NewsSourcesController < ApplicationController
  before_action :set_news_source, only: [:show, :edit, :update, :destroy]

  # GET /news_sources
  # GET /news_sources.json
  def index
    @news_sources = NewsSource.all
  end

  # GET /news_sources/1
  # GET /news_sources/1.json
  def show
  end

  # GET /news_sources/new
  def new
    @news_source = NewsSource.new
  end

  # GET /news_sources/1/edit
  def edit
  end

  # POST /news_sources
  # POST /news_sources.json
  def create
    @news_source = NewsSource.new(news_source_params)

    respond_to do |format|
      if @news_source.save
        format.html { redirect_to @news_source, notice: 'News source was successfully created.' }
        format.json { render :show, status: :created, location: @news_source }
      else
        format.html { render :new }
        format.json { render json: @news_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_sources/1
  # PATCH/PUT /news_sources/1.json
  def update
    respond_to do |format|
      if @news_source.update(news_source_params)
        format.html { redirect_to @news_source, notice: 'News source was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_source }
      else
        format.html { render :edit }
        format.json { render json: @news_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_sources/1
  # DELETE /news_sources/1.json
  def destroy
    @news_source.destroy
    respond_to do |format|
      format.html { redirect_to news_sources_url, notice: 'News source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_source
      @news_source = NewsSource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_source_params
      params.require(:news_source).permit(:name, :host_name, :favicon)
    end
end

app/helpers/news_sources_helper.rb
module NewsSourcesHelper
end

app/views/news_sources/_form.html.erb
<%= form_for(@news_source) do |f| %>
  <% if @news_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_source.errors.count, "error") %> prohibited this news_source from being saved:</h2>

      <ul>
      <% @news_source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :host_name %><br>
    <%= f.text_field :host_name %>
  </div>
  <div class="field">
    <%= f.label :favicon %><br>
    <%= f.text_field :favicon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_sources/edit.html.erb
<h1>Editing News Source</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_source %> |
<%= link_to 'Back', news_sources_path %>

app/views/news_sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing News Sources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Host name</th>
      <th>Favicon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_sources.each do |news_source| %>
      <tr>
        <td><%= news_source.name %></td>
        <td><%= news_source.host_name %></td>
        <td><%= news_source.favicon %></td>
        <td><%= link_to 'Show', news_source %></td>
        <td><%= link_to 'Edit', edit_news_source_path(news_source) %></td>
        <td><%= link_to 'Destroy', news_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News source', new_news_source_path %>

app/views/news_sources/new.html.erb
<h1>New News Source</h1>

<%= render 'form' %>

<%= link_to 'Back', news_sources_path %>

app/views/news_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @news_source.name %>
</p>

<p>
  <strong>Host name:</strong>
  <%= @news_source.host_name %>
</p>

<p>
  <strong>Favicon:</strong>
  <%= @news_source.favicon %>
</p>

<%= link_to 'Edit', edit_news_source_path(@news_source) %> |
<%= link_to 'Back', news_sources_path %>