config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end
  resources :news_items
  resources :news_sources
  get 'home/index'
  mount_griddler

  root 'home#index'

end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
	validates :url, presence: true
	belongs_to :user
	acts_as_taggable

	def self.recent
		order(created_at: :desc)
	end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_action :set_news_item, only: [:show, :edit, :update, :destroy]

  # GET /news_items
  # GET /news_items.json
  def index
    @news_items = NewsItem.all
  end

  # GET /news_items/1
  # GET /news_items/1.json
  def show
  end

  # GET /news_items/new
  def new
    @news_item = NewsItem.new
  end

  # GET /news_items/1/edit
  def edit
  end

  # POST /news_items
  # POST /news_items.json
  def create
    @news_item = NewsItem.new(news_item_params)
    page = LinkThumbnailer.generate(@news_item['url'])
    @news_item.title = page.title
    @news_item.favicon = page.favicon
    @news_item.description = page.description
    @news_item.main_image = page.images.first.src.to_s
    @news_item.user = current_user
    respond_to do |format|
      if @news_item.save
        format.html { redirect_to root_path, notice: 'News item was successfully created.' }
        format.json { render :show, status: :created, location: @news_item }
      else
        format.html { render :new }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_items/1
  # PATCH/PUT /news_items/1.json
  def update
    respond_to do |format|
      if @news_item.update(news_item_params)
        format.html { redirect_to @news_item, notice: 'News item was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_item }
      else
        format.html { render :edit }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_items/1
  # DELETE /news_items/1.json
  def destroy
    @news_item.destroy
    respond_to do |format|
      format.html { redirect_to news_items_url, notice: 'News item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_item
      @news_item = NewsItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_item_params
      params.require(:news_item).permit(:tag_list, :title, :favicon, :description, :main_image, :url)
    end
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/views/news_items/_form.html.erb
<%= form_for(@news_item) do |f| %>
  <% if @news_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_item.errors.count, "error") %> prohibited this news_item from being saved:</h2>

      <ul>
      <% @news_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :favicon %><br>
    <%= f.text_field :favicon %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :main_image %><br>
    <%= f.text_area :main_image %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_items/edit.html.erb
<h1>Editing News Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_item %> |
<%= link_to 'Back', news_items_path %>

app/views/news_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing News Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Favicon</th>
      <th>Description</th>
      <th>Main image</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_items.each do |news_item| %>
      <tr>
        <td><%= news_item.title %></td>
        <td><%= news_item.favicon %></td>
        <td><%= news_item.description %></td>
        <td><%= news_item.main_image %></td>
        <td><%= news_item.url %></td>
        <td><%= link_to 'Show', news_item %></td>
        <td><%= link_to 'Edit', edit_news_item_path(news_item) %></td>
        <td><%= link_to 'Destroy', news_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News item', new_news_item_path %>

app/views/news_items/new.html.erb
<h1>New News Item</h1>

<%= render 'form' %>

<%= link_to 'Back', news_items_path %>

app/views/news_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news_item.title %>
</p>

<p>
  <strong>Favicon:</strong>
  <%= @news_item.favicon %>
</p>

<p>
  <strong>Description:</strong>
  <%= @news_item.description %>
</p>

<p>
  <strong>Main image:</strong>
  <%= @news_item.main_image %>
</p>

<p>
  <strong>Url:</strong>
  <%= @news_item.url %>
</p>

<%= link_to 'Edit', edit_news_item_path(@news_item) %> |
<%= link_to 'Back', news_items_path %>